# Generated by Django 2.2.20 on 2021-05-18 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='apellido')),
                ('domicilio', models.CharField(max_length=100, verbose_name='domicilio')),
                ('dni', models.IntegerField(verbose_name='DNI Cliente')),
                ('tpo_cliente', models.CharField(choices=[('CORPORATIVO', 'CORPORATIVO'), ('INDIVIDUO', 'INDIVIDUO')], max_length=20, verbose_name='tipo de cliente')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Propiedades',
            fields=[
                ('pid', models.AutoField(help_text='Identificación de propiedad', primary_key=True, serialize=False, unique=True, verbose_name='PID')),
                ('nombrep', models.CharField(max_length=50, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=100, verbose_name='direccion')),
                ('superficie', models.CharField(help_text='Superficie medida en m2', max_length=50, verbose_name='Superficie')),
                ('piso', models.IntegerField(verbose_name='Piso')),
                ('dpto', models.CharField(max_length=4, verbose_name='Departamento')),
                ('orientacion', models.CharField(choices=[('ESTE', 'Este'), ('OESTE', 'Oeste'), ('NORTE', 'Norte'), ('SUR', 'Sur')], max_length=5, verbose_name='orientacion')),
                ('frente_contra', models.CharField(choices=[('FRENTE', 'Frente'), ('CONTRAFRENTE', 'Contrafrente')], max_length=15, verbose_name='frente-contrafrente')),
                ('dormitorios', models.IntegerField(verbose_name='Dormitorios')),
                ('baños', models.IntegerField(verbose_name='Baños')),
                ('cocina', models.BooleanField(verbose_name='Cocina')),
                ('comedor', models.BooleanField(verbose_name='Comedor')),
                ('cochera', models.BooleanField(verbose_name='Cochera')),
                ('balcon', models.BooleanField(verbose_name='Balcon')),
                ('observaciones', models.TextField(help_text='Datos adicionales para la propiedad', max_length=300, verbose_name='observaciones')),
                ('expensa', models.DecimalField(decimal_places=2, help_text='Precio aproximado', max_digits=16, verbose_name='Expensa')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Valor neto total de la propiedad/alquiler', max_digits=16, verbose_name='Precio')),
                ('tpo_propiedad', models.CharField(choices=[('VENTA', 'Venta'), ('ALQUILER', 'Alquiler')], max_length=5, verbose_name='Tipo de propiedad')),
                ('disponible', models.BooleanField(verbose_name='Disponible')),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_pay', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID. Pago')),
                ('medio_pago', models.CharField(choices=[('TRANSFERENCIA', 'Transferencia'), ('EFECTIVO', 'Efectivo')], max_length=5, verbose_name='Medio de Pago')),
                ('nya_cliente', models.CharField(max_length=100, verbose_name='Nombre')),
                ('dni_cli', models.IntegerField(verbose_name='DNI Cliente')),
                ('estado_pago', models.CharField(choices=[('PAGADO', 'Pagado'), ('PENDIENTE', 'Pendiente')], max_length=20, verbose_name='Estado de Pago')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Propiedades')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JefeComercializacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JefeAdministracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmpleadoMarketing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.IntegerField(unique=True, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=100, verbose_name='Nombre cliente')),
                ('num_cliente', models.IntegerField(verbose_name='Cel./Tel.')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('propiedad', models.CharField(max_length=50, verbose_name='Propiedad')),
                ('fecha_cita', models.DateField(blank=True, null=True, verbose_name='Fecha de cita')),
                ('hora_cita', models.TimeField(blank=True, null=True, verbose_name='Hora de cita')),
                ('estado_cita', models.BooleanField(blank=True, null=True, verbose_name='Atendido/a')),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Agente')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
            },
        ),
        migrations.CreateModel(
            name='Cajera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
