# Generated by Django 2.2.20 on 2021-05-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_propiedades_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedades',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='imagen de propiedad'),
        ),
        migrations.AlterField(
            model_name='propiedades',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Datos adicionales para la propiedad', max_length=300, null=True, verbose_name='observaciones'),
        ),
        migrations.AlterField(
            model_name='propiedades',
            name='tpo_propiedad',
            field=models.CharField(choices=[('VENTA', 'Venta'), ('ALQUILER', 'Alquiler')], max_length=15, verbose_name='Tipo de propiedad'),
        ),
    ]
