# Generated by Django 2.2.20 on 2021-05-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210518_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citas',
            name='id',
        ),
        migrations.AlterField(
            model_name='citas',
            name='identificacion',
            field=models.AutoField(help_text='Identificación de propiedad', primary_key=True, serialize=False, unique=True, verbose_name='ID Cita'),
        ),
    ]
