# Generated by Django 2.2.20 on 2021-05-18 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210518_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Propiedades'),
        ),
    ]
