# Generated by Django 2.2.20 on 2021-05-18 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210518_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='medio_pago',
            field=models.CharField(choices=[('TRANSFERENCIA', 'Transferencia'), ('EFECTIVO', 'Efectivo')], max_length=25, verbose_name='Medio de Pago'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='nya_cliente',
            field=models.CharField(max_length=100, verbose_name='Nombre Cliente'),
        ),
    ]
